---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksctl-test
  region: us-east-1

nodeGroups:
  - name: ng1-piblic
    instanceType: t3.micro
    desiredCapacity: 2
    volumeSize: 80
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
managedNodeGroups:
  - name: ng2-managed
    instanceType: t3.micro
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 100
    ssh:
      publicKeyPath: ~/.ssh/ec2_id_rsa.pub